// src/cssPropertyKeys.ts
import { CSSProperties } from 'react';

// Define a type that includes both standard CSS properties and custom vendor-prefixed properties
type ExtendedCSSProperties = CSSProperties & {
  [key: string]: any; // Allow any string key for custom properties
};

// Helper function to convert camelCase vendor-prefixed properties to kebab-case
export const vendorPrefixToKebabCase = (property: string): string => {
  // Handle custom properties (CSS variables)
  if (property.startsWith('--')) {
    return property;
  }

  // Handle webkit, moz, ms prefixes with uppercase first letter after prefix (WebkitTextFillColor)
  if (/^(Webkit|Moz|Ms|O)[A-Z]/.test(property)) {
    const prefix =
      property.match(/^(Webkit|Moz|Ms|O)/)?.[0]?.toLowerCase() || '';
    const restOfProperty = property.slice(prefix.length);
    return `-${prefix}-${restOfProperty
      .replace(/([A-Z])/g, '-$1')
      .toLowerCase()}`;
  }

  // Handle webkit, moz, ms prefixes with lowercase first letter (webkitTextFillColor)
  if (/^(webkit|moz|ms|o)[A-Z]/.test(property)) {
    const prefix = property.match(/^(webkit|moz|ms|o)/)?.[0] || '';
    const restOfProperty = property.slice(prefix.length);
    return `-${prefix}-${restOfProperty
      .replace(/([A-Z])/g, '-$1')
      .toLowerCase()}`;
  }

  // Regular camelCase to kebab-case
  return property.replace(/([A-Z])/g, '-$1').toLowerCase();
};

export const cssPropertyKeys: Array<keyof ExtendedCSSProperties> = [
  'alignContent',
  'alignItems',
  'alignSelf',
  'animation',
  'animationDelay',
  'animationDirection',
  'animationDuration',
  'animationFillMode',
  'animationIterationCount',
  'animationName',
  'animationPlayState',
  'animationTimingFunction',
  'backfaceVisibility',
  'background',
  'backgroundAttachment',
  'backgroundBlendMode',
  'backgroundClip',
  'backgroundColor',
  'backgroundImage',
  'backgroundOrigin',
  'backgroundPosition',
  'backgroundRepeat',
  'backgroundSize',
  'border',
  'borderBottom',
  'borderBottomColor',
  'borderBottomLeftRadius',
  'borderBottomRightRadius',
  'borderBottomStyle',
  'borderBottomWidth',
  'borderCollapse',
  'borderColor',
  'borderImage',
  'borderImageOutset',
  'borderImageRepeat',
  'borderImageSlice',
  'borderImageSource',
  'borderImageWidth',
  'borderLeft',
  'borderLeftColor',
  'borderLeftStyle',
  'borderLeftWidth',
  'borderRadius',
  'borderRight',
  'borderRightColor',
  'borderRightStyle',
  'borderRightWidth',
  'borderSpacing',
  'borderStyle',
  'borderTop',
  'borderTopColor',
  'borderTopLeftRadius',
  'borderTopRightRadius',
  'borderTopStyle',
  'borderTopWidth',
  'borderWidth',
  'bottom',
  'boxShadow',
  'boxSizing',
  'captionSide',
  'caretColor',
  'clear',
  'clip',
  'color',
  'columnCount',
  'columnFill',
  'columnGap',
  'columnRule',
  'columnRuleColor',
  'columnRuleStyle',
  'columnRuleWidth',
  'columns',
  'columnSpan',
  'columnWidth',
  'content',
  'counterIncrement',
  'counterReset',
  'cursor',
  'direction',
  'display',
  'emptyCells',
  'filter',
  'flex',
  'flexBasis',
  'flexDirection',
  'flexFlow',
  'flexGrow',
  'flexShrink',
  'flexWrap',
  'float',
  'font',
  'fontFamily',
  'fontSize',
  'fontStyle',
  'fontVariant',
  'fontWeight',
  'gap',
  'grid',
  'gridArea',
  'gridAutoColumns',
  'gridAutoFlow',
  'gridAutoRows',
  'gridColumn',
  'gridColumnEnd',
  'gridColumnGap',
  'gridColumnStart',
  'gridGap',
  'gridRow',
  'gridRowEnd',
  'gridRowGap',
  'gridRowStart',
  'gridTemplate',
  'gridTemplateAreas',
  'gridTemplateColumns',
  'gridTemplateRows',
  'height',
  'hyphens',
  'imageRendering',
  'inlineSize',
  'isolation',
  'justifyContent',
  'justifyItems',
  'justifySelf',
  'left',
  'letterSpacing',
  'lineHeight',
  'listStyle',
  'listStyleImage',
  'listStylePosition',
  'listStyleType',
  'margin',
  'marginBlockEnd',
  'marginBlockStart',
  'marginBottom',
  'marginInlineEnd',
  'marginInlineStart',
  'marginLeft',
  'marginRight',
  'marginTop',
  'mask',
  'maskType',
  'maxBlockSize',
  'maxHeight',
  'maxInlineSize',
  'maxWidth',
  'minBlockSize',
  'minHeight',
  'minInlineSize',
  'minWidth',
  'mixBlendMode',
  'objectFit',
  'objectPosition',
  'opacity',
  'order',
  'outline',
  'outlineColor',
  'outlineOffset',
  'outlineStyle',
  'outlineWidth',
  'overflow',
  'overflowAnchor',
  'overflowWrap',
  'overflowX',
  'overflowY',
  'padding',
  'paddingBlockEnd',
  'paddingBlockStart',
  'paddingBottom',
  'paddingInlineEnd',
  'paddingInlineStart',
  'paddingLeft',
  'paddingRight',
  'paddingTop',
  'pageBreakAfter',
  'pageBreakBefore',
  'pageBreakInside',
  'perspective',
  'perspectiveOrigin',
  'pointerEvents',
  'position',
  'quotes',
  'resize',
  'right',
  'rotate',
  'rowGap',
  'scale',
  'scrollBehavior',
  'scrollMargin',
  'scrollMarginBlock',
  'scrollMarginBlockEnd',
  'scrollMarginBlockStart',
  'scrollMarginBottom',
  'scrollMarginInline',
  'scrollMarginInlineEnd',
  'scrollMarginInlineStart',
  'scrollMarginLeft',
  'scrollMarginRight',
  'scrollMarginTop',
  'scrollPadding',
  'scrollPaddingBlock',
  'scrollPaddingBlockEnd',
  'scrollPaddingBlockStart',
  'scrollPaddingBottom',
  'scrollPaddingInline',
  'scrollPaddingInlineEnd',
  'scrollPaddingInlineStart',
  'scrollPaddingLeft',
  'scrollPaddingRight',
  'scrollPaddingTop',
  'scrollSnapAlign',
  'scrollSnapMargin',
  'scrollSnapMarginBottom',
  'scrollSnapMarginLeft',
  'scrollSnapMarginRight',
  'scrollSnapMarginTop',
  'scrollSnapStop',
  'scrollSnapType',
  'shapeImageThreshold',
  'shapeMargin',
  'shapeOutside',
  'tabSize',
  'tableLayout',
  'textAlign',
  'textAlignLast',
  'textCombineUpright',
  'textDecoration',
  'textDecorationColor',
  'textDecorationLine',
  'textDecorationStyle',
  'textIndent',
  'textJustify',
  'textOverflow',
  'textShadow',
  'textTransform',
  'top',
  'transform',
  'transformOrigin',
  'transformStyle',
  'transition',
  'transitionDelay',
  'transitionDuration',
  'transitionProperty',
  'transitionTimingFunction',
  'translate',
  'unicodeBidi',
  'userSelect',
  'verticalAlign',
  'visibility',
  'whiteSpace',
  'widows',
  'width',
  'wordBreak',
  'wordSpacing',
  'wordWrap',
  'writingMode',
  'zIndex',

  // Vendor-prefixed properties (uppercase first letter)
  'WebkitAppearance',
  'WebkitBackfaceVisibility',
  'WebkitBorderImage',
  'WebkitBoxShadow',
  'WebkitBoxSizing',
  'WebkitColumnCount',
  'WebkitColumnRule',
  'WebkitColumnWidth',
  'WebkitColumns',
  'WebkitFlex',
  'WebkitFlexBasis',
  'WebkitFlexDirection',
  'WebkitFlexFlow',
  'WebkitFlexGrow',
  'WebkitFlexShrink',
  'WebkitFlexWrap',
  'WebkitFontFeatureSettings',
  'WebkitFontSmoothing',
  'WebkitHyphens',
  'WebkitJustifyContent',
  'WebkitLineClamp',
  'WebkitMask',
  'WebkitOverflowScrolling',
  'WebkitPerspective',
  'WebkitPerspectiveOrigin',
  'WebkitTapHighlightColor',
  'WebkitTextFillColor',
  'WebkitTextSizeAdjust',
  'WebkitTextStroke',
  'WebkitTextStrokeColor',
  'WebkitTextStrokeWidth',
  'WebkitTransform',
  'WebkitTransformOrigin',
  'WebkitTransformStyle',
  'WebkitTransition',
  'WebkitTransitionDelay',
  'WebkitTransitionDuration',
  'WebkitTransitionProperty',
  'WebkitTransitionTimingFunction',
  'WebkitUserSelect',
  'WebkitBackgroundClip',

  // Vendor-prefixed properties (lowercase first letter)
  'webkitAppearance',
  'webkitBackfaceVisibility',
  'webkitBorderImage',
  'webkitBoxShadow',
  'webkitBoxSizing',
  'webkitColumnCount',
  'webkitColumnRule',
  'webkitColumnWidth',
  'webkitColumns',
  'webkitFlex',
  'webkitFlexBasis',
  'webkitFlexDirection',
  'webkitFlexFlow',
  'webkitFlexGrow',
  'webkitFlexShrink',
  'webkitFlexWrap',
  'webkitFontFeatureSettings',
  'webkitFontSmoothing',
  'webkitHyphens',
  'webkitJustifyContent',
  'webkitLineClamp',
  'webkitMask',
  'webkitOverflowScrolling',
  'webkitPerspective',
  'webkitPerspectiveOrigin',
  'webkitTapHighlightColor',
  'webkitTextFillColor',
  'webkitTextSizeAdjust',
  'webkitTextStroke',
  'webkitTextStrokeColor',
  'webkitTextStrokeWidth',
  'webkitTransform',
  'webkitTransformOrigin',
  'webkitTransformStyle',
  'webkitTransition',
  'webkitTransitionDelay',
  'webkitTransitionDuration',
  'webkitTransitionProperty',
  'webkitTransitionTimingFunction',
  'webkitUserSelect',
  'webkitBackgroundClip',

  // Mozilla-specific properties
  'MozAppearance',
  'MozBackfaceVisibility',
  'MozBorderImage',
  'MozBoxShadow',
  'MozBoxSizing',
  'MozColumnCount',
  // 'MozColumnGap',
  'MozColumnRule',
  'MozColumnWidth',
  'MozColumns',
  'MozFontFeatureSettings',
  'MozHyphens',
  'MozOsxFontSmoothing',
  'MozPerspective',
  'MozPerspectiveOrigin',
  'MozTextSizeAdjust',
  // 'MozTransform',
  'MozTransformOrigin',
  'MozTransformStyle',
  'MozTransition',
  'MozTransitionDelay',
  'MozTransitionDuration',
  'MozTransitionProperty',
  'MozTransitionTimingFunction',
  'MozUserSelect',

  // Microsoft-specific properties
  // 'msFlexAlign',
  'msFlexDirection',
  // 'msFlexFlow',
  // 'msFlexItemAlign',
  // 'msFlexLinePack',
  // 'msFlexNegative',
  // 'msFlexOrder',
  // 'msFlexPack',
  'msFlexPositive',
  // 'msFlexPreferredSize',
  // 'msFlexWrap',
  // 'msGridColumn',
  // 'msGridColumnAlign',
  // 'msGridColumnSpan',
  'msGridColumns',
  // 'msGridRow',
  // 'msGridRowAlign',
  // 'msGridRowSpan',
  'msGridRows',
  'msHighContrastAdjust',
  'msHyphens',
  'msOverflowStyle',
  'msScrollbar3dlightColor',
  'msScrollbarArrowColor',
  'msScrollbarBaseColor',
  'msScrollbarDarkshadowColor',
  'msScrollbarFaceColor',
  'msScrollbarHighlightColor',
  'msScrollbarShadowColor',
  'msScrollbarTrackColor',
  // 'msTextSizeAdjust',
  'msTransform',
  'msTransformOrigin',
  'msTransition',
  'msTransitionDelay',
  'msTransitionDuration',
  'msTransitionProperty',
  'msTransitionTimingFunction',
  'msUserSelect',

  // Opera-specific properties
  'OAnimation',
  'OAnimationDelay',
  'OAnimationDirection',
  'OAnimationDuration',
  'OAnimationFillMode',
  'OAnimationIterationCount',
  'OAnimationName',
  'OAnimationPlayState',
  'OAnimationTimingFunction',
  'OBackgroundSize',
  'OBorderImage',
  'OObjectFit',
  'OObjectPosition',
  'OTransform',
  'OTransformOrigin',
  'OTransition',
  'OTransitionDelay',
  'OTransitionDuration',
  'OTransitionProperty',
  'OTransitionTimingFunction',

  // Add any additional CSS properties as needed
];

export const numericCssProperties = new Set<string>([
  'border-bottom-left-radius',
  'border-bottom-right-radius',
  'border-bottom-width',
  'border-left-width',
  'border-radius',
  'border-right-width',
  'border-spacing',
  'border-top-left-radius',
  'border-top-right-radius',
  'border-top-width',
  'border-width',
  'bottom',
  'column-gap',
  'column-rule-width',
  'column-width',
  'font-size',
  'gap',
  'height',
  'left',
  'letter-spacing',
  'line-height',
  'margin',
  'margin-bottom',
  'margin-left',
  'margin-right',
  'margin-top',
  'max-height',
  'max-width',
  'min-height',
  'min-width',
  'outline-offset',
  'outline-width',
  'padding',
  'padding-bottom',
  'padding-left',
  'padding-right',
  'padding-top',
  'perspective',
  'right',
  'row-gap',
  'text-indent',
  'top',
  'width',

  // Vendor-prefixed properties that need pixel values
  '-webkit-border-radius',
  '-webkit-border-bottom-left-radius',
  '-webkit-border-bottom-right-radius',
  '-webkit-border-top-left-radius',
  '-webkit-border-top-right-radius',
  '-webkit-column-gap',
  '-webkit-column-width',
  '-webkit-margin-bottom',
  '-webkit-margin-left',
  '-webkit-margin-right',
  '-webkit-margin-top',
  '-webkit-padding-bottom',
  '-webkit-padding-left',
  '-webkit-padding-right',
  '-webkit-padding-top',
  '-webkit-perspective',
  '-webkit-text-indent',

  '-moz-border-radius',
  '-moz-border-bottom-left-radius',
  '-moz-border-bottom-right-radius',
  '-moz-border-top-left-radius',
  '-moz-border-top-right-radius',
  '-moz-column-gap',
  '-moz-column-width',
  '-moz-margin-bottom',
  '-moz-margin-left',
  '-moz-margin-right',
  '-moz-margin-top',
  '-moz-padding-bottom',
  '-moz-padding-left',
  '-moz-padding-right',
  '-moz-padding-top',
  '-moz-perspective',
  '-moz-text-indent',

  '-ms-column-gap',
  '-ms-column-width',
  '-ms-margin-bottom',
  '-ms-margin-left',
  '-ms-margin-right',
  '-ms-margin-top',
  '-ms-padding-bottom',
  '-ms-padding-left',
  '-ms-padding-right',
  '-ms-padding-top',
  '-ms-text-indent',
]);
