const ts = require('typescript');
const path = require('path');

/**
 * Utility function to log errors and exit.
 */
function logErrorAndExit(message) {
  console.error(message);
  process.exit(1);
}

/**
 * Main function to generate CSS property keys.
 */
function generateCssPropertyKeys() {
  try {
    // Resolve the path to React's type definitions
    const reactDtsPath = path.resolve('./node_modules/@types/react/index.d.ts');

    // Create a TypeScript program to analyze the types
    const program = ts.createProgram([reactDtsPath], {
      target: ts.ScriptTarget.ES5,
      module: ts.ModuleKind.CommonJS,
    });
    const checker = program.getTypeChecker();

    // Get the source file
    const source = program.getSourceFile(reactDtsPath);
    console.log(source);
    if (!source) {
      logErrorAndExit('Could not find React type definitions.');
    }

    let cssPropertyKeys = [];

    // Traverse the AST to find the CSSProperties interface
    ts.forEachChild(source, (node) => {
      // Look for module declarations named 'CSS'
      if (ts.isModuleDeclaration(node) && node.name.text === 'CSS') {
        ts.forEachChild(node, (moduleBlock) => {
          if (ts.isModuleBlock(moduleBlock)) {
            ts.forEachChild(moduleBlock, (innerNode) => {
              // Look for interface declarations named 'CSSProperties'
              if (
                ts.isInterfaceDeclaration(innerNode) &&
                innerNode.name.text === 'CSSProperties'
              ) {
                innerNode.members.forEach((member) => {
                  if (ts.isPropertySignature(member) && member.name) {
                    const name = member.name.getText();
                    // Remove quotes if any
                    cssPropertyKeys.push(name.replace(/['"]/g, ''));
                  }
                });
              }
            });
          }
        });
      }
    });

    if (cssPropertyKeys.length === 0) {
      logErrorAndExit(
        'No CSSProperties interface found in React type definitions.'
      );
    }

    // Sort the keys alphabetically for consistency
    cssPropertyKeys.sort();

    // Define the output path
    const outputPath = path.join(__dirname, '../src/cssPropertyKeys.js');

    // Create the content for the output file
    const fileContent = `// This file is auto-generated by generateCssPropertyKeys.js
// Do not edit this file manually.

const cssPropertyKeys = ${JSON.stringify(cssPropertyKeys, null, 2)};

module.exports = cssPropertyKeys;
`;

    // Ensure the src directory exists
    const srcDir = path.join(__dirname, '../src');
    if (!fs.existsSync(srcDir)) {
      fs.mkdirSync(srcDir);
    }

    // Write the file
    fs.writeFileSync(outputPath, fileContent, 'utf8');
    console.log(`CSS property keys generated at ${outputPath}`);
  } catch (error) {
    logErrorAndExit(`An error occurred: ${error.message}`);
  }
}

// Execute the main function
generateCssPropertyKeys();
